# Wallet urls
###
GET http://127.0.0.1:8000/wallet-account/create/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3Mzc4Nzk3LCJpYXQiOjE3MzczNzY5OTcsImp0aSI6IjgyZTJlMzY2Y2E1NzQyY2JiMjQ1YzQwMWZhODEzMjA3IiwidXNlcl9pZCI6MX0.m0zjfK7WKlrwgZzhb23gM8qCMaHrg22y5cPLP4Nw1h0

{"username": "Charles", "password":"12345678"}

###
DELETE http://localhost:8000/wallet-account/2/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM3MjE2MDM0LCJpYXQiOjE3MzcyMTQyMzQsImp0aSI6ImNmOWJlNGNlOTQ2MDQ5YzE4NGI0MTBjNzIxNmJhMmY3IiwidXNlcl9pZCI6NX0.KwZct7dZ0zfB3CjokvZ0sweE23b7bSmvQ73RYyy4X84

{"balance": 1}

# JWT Tokens / api
###
POST http://localhost:8000/api/token/
Content-Type: application/json

{"username": "Charles", "password":"12345678"}


# User creation / user
###
POST http://localhost:8000/user/register/
Content-Type: application/json

{"username": "Charles", "password":"12345678"}
