# Generated by Django 5.1.4 on 2025-01-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="currency",
            field=models.CharField(
                choices=[("PHP", "PHP"), ("USD", "USD")], default="PHP", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.BigIntegerField(max_length=1000000),
        ),
    ]
