# Generated by Django 5.1.4 on 2025-01-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0002_account_currency_alter_account_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.BigIntegerField(default=0),
        ),
    ]
