# Generated by Django 5.1.4 on 2025-01-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0003_alter_account_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
