# Generated by Django 5.1.4 on 2025-01-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet", "0004_alter_account_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="name",
            field=models.CharField(default="Wallet", max_length=20),
        ),
    ]
